# Generated by Django 5.0.3 on 2024-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="간단하게 설명할 문구, 빈칸가능",
                max_length=100,
                verbose_name="설명",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="modify_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, help_text="제목의 별칭", unique=True, verbose_name="SLUG"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50, verbose_name="제목"),
        ),
    ]
